### ISSUE TITLE
Manual upload not possible and still "Some cool guy" issue

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#97]
Testserver: spot.mpdl.mpg.de/rest and qa-gluons
Test date: 27.03.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: manual upload after automatic upload

-> deavticate automatic upload -> select items from local -> "manual upload" -> "Choose collection" ->

Observation:
![some cool guy ii](https://cloud.githubusercontent.com/assets/14921701/24354351/ba85529e-12f1-11e7-9c27-9721c60568d4.jpg)

-> choose collection ->  items not uploaded (upload task stays  as 0%)

reproducible for qa-gluons and spot

see also #75 (closed ticket)

Expected result: correct creator of collection displayed and items uploaded

**Comment by soultice** [comment]
This bug is fixed on the development branch, unfortunately there is a lot of code dependent on this (and some other) small changes. The bugs resolving from these changes are unfortunately deeply integrated in the code and will take some time until they can be completely resolved, which is the reason why the development branch has not been merged onto the master branch yet.

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg.de
Test date: 28.09.2017
Device: Tablet Nexus 9 Android 5.1.1.

not reproducible anymore
